-- Superseded by the first-run setup code (2026-10-10). Intentionally empty.
-- New databases create their first admin through the app's setup screen
-- (POST /setup/admin, guarded by the SETUP_CODE environment variable).
-- Existing databases are baselined past this file by scripts/migrate.ts.
